name: Prettier

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14' # Specify the Node.js version
      - run: npm install
      - run: npm run prettier
